# Generated by Django 4.2.6 on 2023-10-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='favico',
            new_name='favicon',
        ),
    ]
